using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Server.Mindray
{
    public enum HL7_WAVE_ENUM
    {
        [Description("CO2, Airway")] MDC_CONC_AWAY_CO2 = 151700,
        [Description("O2, Airway ")] MDC_CONC_AWAY_02 = 151908,
        [Description("N2O, Airway")]  MDC_CONC_AWAY_N20 = 152048,
        [Description("N2O, Airway")] MDC_CONC_AWAY_AGENT = 152456,
        [Description("Desflurane, Airway")] MDC_CONC_AWAY_DESFL = 152024,
        [Description("Enflurane, Airway")] MDC_CONC_AWAY_ENFL = 152028,
        [Description("Halothane, Airway")] MDC_CONC_AWAY_HALOTH = 152032,
        [Description("Halothane, Airway")] MDC_CONC_AWAY_SEVOFL = 152036,
        [Description("Isoflurane, Airway")] MDC_CONC_AWAY_ISOFL = 152040,
        [Description("Pressure, Airway")] MDC_PRESS_AWAY = 151792,
        [Description("Flow, Airway")] MDC_FLOW_AWAY = 151764,
        [Description("Volume, Airway ")] MDC_VOL_AWAY = 152708,
        [Description("ECG Lead I")] MDC_ECG_ELEC_POTL_I = 131329,
        [Description("ECG Lead II")] MDC_ECG_ELEC_POTL_II = 131330,
        [Description("ECG Lead III")] MDC_ECG_ELEC_POTL_III = 131389,
        [Description("ECG Lead aVL")] MDC_ECG_ELEC_POTL_AVL = 131391,
        [Description("ECG Lead aVR")] MDC_ECG_ELEC_POTL_AVR = 131390,
        [Description("ECG Lead aVF")] MDC_ECG_ELEC_POTL_AVF = 131392,
        [Description("ECG Lead V")] MDC_ECG_ELEC_POTL_V = 131395,
        [Description("ECG Lead V1")] MDC_ECG_ELEC_POTL_V1 = 131331,
        [Description("ECG Lead V2")] MDC_ECG_ELEC_POTL_V2 = 131332,
        [Description("ECG Lead V3")] MDC_ECG_ELEC_POTL_V3 = 131333,
        [Description("ECG Lead V4")] MDC_ECG_ELEC_POTL_V4 = 131334,
        [Description("ECG Lead V5")] MDC_ECG_ELEC_POTL_V5 = 131335,
        [Description("ECG Lead V6 ")] MDC_ECG_ELEC_POTL_V6 = 131336,
        [Description("Transthoracic Impedance")] MDC_IMPED_TTHOR = 151780,
        [Description("Invasive Blood Pressure")] MDC_PRESS_BLD = 150016,
        [Description("Arterial Blood Pressure ")] MDC_PRESS_BLD_ART = 150032,
        [Description("Umbilical Arterial Blood Pressure")] MDC_PRESS_BLD_ART_UMB = 150056,
        [Description("Left Ventricle Blood Pressure")] MDC_PRESS_BLD_VENT_LEFT = 150100,
        [Description("Pulmonary Arterial Blood Pressure")] MDC_PRESS_BLD_ART_PULM = 150044,
        [Description("Central Venous Blood Pressure")] MDC_PRESS_BLD_VEN_CENT = 150084,
        [Description("Intra Cranial Pressure")] MDC_PRESS_INTRA_CRAN = 153608,
        [Description("Left Atria Blood Pressure")] MDC_PRESS_BLD_ATR_LEFT = 150064,
        [Description("Right Atria Blood Pressure")] MDC_PRESS_BLD_ATR_RIGHT = 150068,
        [Description("Aortic Blood Pressure")] MDC_PRESS_BLD_AORT = 150028,
        [Description("Brachial Arterial Blood Pressure")] MDC_PRESS_BLD_ART_BRACHIAL = 150680,
        [Description("Femoral Arterial Blood Pressure")] MDC_PRESS_BLD_ART_FEMORAL = 150648,
        [Description("Umbilical Venous Blood Pressure")] MDC_PRESS_BLD_VEN_UMB = 150088,
        [Description("EEG")] MDC_EEG_ELEC_POTL_CRTX = 153900,
        [Description("Pleth")] MDC_PULS_OXIM_PLETH = 150452,
        [Description("SpO2 Signal Quality Index")] MDC_SPO2_SIGNAL_QUALITY_INDEX = 160324,
        [Description("Esophageal pressure")] MDC_PRESS_ESOPH = 151820,
        [Description("nspiratory pressuretime product")] MDC_PRESS_TRANSPULM = 153248,
        

        //[Description("ECG Lead I")] MDC_ECG_ELEC_POTL_I = 131329,
        //[Description("ECG Lead II")] MDC_ECG_ELEC_POTL_II = 131330,
        //[Description("ECG Lead III")] MDC_ECG_ELEC_POTL_III = 131389,
        //[Description("ECG Lead aVR")] MDC_ECG_ELEC_POTL_AVR = 131390,
        //[Description("ECG Lead aVL")] MDC_ECG_ELEC_POTL_AVL = 131391,
        //[Description("ECG Lead aVF")] MDC_ECG_ELEC_POTL_AVF = 131392,
        //[Description("ECG Lead V1")] MDC_ECG_ELEC_POTL_V1 = 131331,
        //[Description("ECG Lead V2")] MDC_ECG_ELEC_POTL_V2 = 131332,
        //[Description("ECG Lead V3")] MDC_ECG_ELEC_POTL_V3 = 131333,
        //[Description("ECG Lead V4")] MDC_ECG_ELEC_POTL_V4 = 131334,
        //[Description("ECG Lead V5")] MDC_ECG_ELEC_POTL_V5 = 131335,
        //[Description("ECG Lead V6")] MDC_ECG_ELEC_POTL_V6 = 131336,
        //[Description("ECG Lead V")] MDC_ECG_ELEC_POTL_V = 131395,
        [Description("ECG Lead VB")] MNDRY_ECG_ELEC_POTL_VB = 377,
        //[Description("Pleth")] MDC_PULS_OXIM_PLETH = 150452,
        //[Description("Pleth2")] MDC_PULS_OXIM_PLETH = 150452,
        //[Description("Transthoracic Impedance ")] MDC_IMPED_TTHOR = 151780,
        //[Description("Arterial Blood Pressure")] MDC_PRESS_BLD_ART = 150032,
        //[Description("Arterial Blood Pressure1")] MDC_PRESS_BLD_ART = 150032,
        //[Description("Arterial Blood Pressure2")] MDC_PRESS_BLD_ART = 150032,
        //[Description("Pulmonary Arterial Blood Pressure")] MDC_PRESS_BLD_ART_PULM = 150044,
        //[Description("Central Venous Blood Pressure")] MDC_PRESS_BLD_VEN_CENT = 150084,
        //[Description("Right Atria Blood Pressure")] MDC_PRESS_BLD_ATR_RIGHT = 150068,
        //[Description("Left Atria Blood Pressure")] MDC_PRESS_BLD_ATR_LEFT = 150064,
        //[Description("Intra Cranial Pressure")] MDC_PRESS_INTRA_CRAN = 153608,
        //[Description("Invasive Blood Pressure")] MDC_PRESS_BLD = 150016,
        //[Description("Invasive Blood Pressure1")] MDC_PRESS_BLD = 150016,
        //[Description("Invasive Blood Pressure2")] MDC_PRESS_BLD = 150016,
        //[Description("Invasive Blood Pressure3")] MDC_PRESS_BLD = 150016,
        //[Description("Invasive Blood Pressure4")] MDC_PRESS_BLD = 150016,
        //[Description("Invasive Blood Pressure5")] MDC_PRESS_BLD = 150016,
        //[Description("Invasive Blood Pressure6")] MDC_PRESS_BLD = 150016,
        //[Description("Invasive Blood Pressure7")] MDC_PRESS_BLD = 150016,
        //[Description("Invasive Blood Pressure8")] MDC_PRESS_BLD = 150016,
        //[Description("Aortic Blood Pressure")] MDC_PRESS_BLD_AORT = 150028,
        //[Description("Umbilical Arterial Blood Pressure")] MDC_PRESS_BLD_ART_UMB = 150056,
        //[Description("Brachial Arterial Blood Pressure")] MDC_PRESS_BLD_ART_BRACHIAL = 150680,
        //[Description("Femoral Arterial Blood Pressure")] MDC_PRESS_BLD_ART_FEMORAL = 150648,
        //[Description("Umbilical Venous Blood Pressure")] MDC_PRESS_BLD_VEN_UMB = 150088,
        //[Description("Left Ventricle Blood Pressure")] MDC_PRESS_BLD_VENT_LEFT = 150100,
        //[Description("Arterial Blood Pressure from PiCCO ")] MDC_PRESS_BLD_ART = 150032,
        //[Description("Central Venous Blood Pressure from PiCCO")] MDC_PRESS_BLD_VEN_CENT = 150084,
        [Description("Intra-abdominal Pressure ")] MNDRY_PRESS_INTRA_ABDOM = 284,
        //[Description("CO2 CO2, Airway")] MDC_CONC_AWAY_CO2 = 151700,
        [Description("CO2 O2, Airway")] MDC_CONC_AWAY_O2 = 151908,
        //[Description("GAS CO2, Airway")] MDC_CONC_AWAY_CO2 = 151700,
        //[Description("GAS O2, Airway")] MDC_CONC_AWAY_O2 = 151908,
        [Description("GAS N2O, Airway")] MDC_CONC_AWAY_N2O = 152048,
        //[Description("Primary Agent, Airway")] MDC_CONC_AWAY_AGENT = 152456,
        //[Description("Sencondary Agent, Airway")] MDC_CONC_AWAY_AGENT = 152456,
        //[Description("Halothane, Airway")] MDC_CONC_AWAY_HALOTH = 152032,
        //[Description("Enflurane, Airway")] MDC_CONC_AWAY_ENFL = 152028,
        //[Description("Isoflurane, Airway")] MDC_CONC_AWAY_ISOFL = 152040,
        //[Description("Sevoflurane, Airway")] MDC_CONC_AWAY_SEVOFL = 152036,
        //[Description("Desflurane, Airway")] MDC_CONC_AWAY_DESFL = 152024,
        [Description("BIS EEG")] MNDRY_EEG_ELEC_POTL_BIS = 286,
        [Description("BIS EEG, Temporal")] MNDRY_EEG_ELEC_POTL_BIS_TEMPR = 287,
        [Description("BIS EEG, Eye")] MNDRY_EEG_ELEC_POTL_BIS_EYE = 288,
        //[Description("BIS EEG, Left Temporal")] MNDRY_EEG_ELEC_POTL_BIS_TEMPR = 287,
        //[Description("BIS EEG, Left Eye")] MNDRY_EEG_ELEC_POTL_BIS_EYE = 288,
        //[Description("BIS EEG, Right Temporal")] MNDRY_EEG_ELEC_POTL_BIS_TEMPR = 287,
        //[Description("BIS EEG, Right Eye")] MNDRY_EEG_ELEC_POTL_BIS_EYE = 288,
        //[Description("Airway Pressure")] MDC_PRESS_AWAY = 151792,
        //[Description("Airway Flow")] MDC_FLOW_AWAY = 151764,
        //[Description("Airway Volume")] MDC_VOL_AWAY = 152708,
        [Description("Impedance Cardiography Impedance")] MNDRY_ICG_IMP = 290,
        //[Description("EEG")] MDC_EEG_ELEC_POTL_CRTX = 153900,
        //[Description("EEG1")] MDC_EEG_ELEC_POTL_CRTX = 153900,
        //[Description("EEG2")] MDC_EEG_ELEC_POTL_CRTX = 153900,
        //[Description("EEG3")] MDC_EEG_ELEC_POTL_CRTX = 153900,
        //[Description("EEG4")] MDC_EEG_ELEC_POTL_CRTX = 153900,
        //[Description("ANES AA ")] MDC_CONC_AWAY_AGENT = 152456,
        //[Description("ANES AA2 ")] MDC_CONC_AWAY_AGENT = 152456,
        //[Description("ANES BIS ")] MNDRY_EEG_ELEC_POTL_BIS = 286,
        //[Description("ANES CO2 ")] MDC_CONC_AWAY_CO2 = 151700,
        //[Description("ANES DES ")] MDC_CONC_AWAY_DESFL = 152024,
        //[Description("ANES ENF ")] MDC_CONC_AWAY_ENFL = 152028,
        //[Description("ANES HAL ")] MDC_CONC_AWAY_HALOTH = 152032,
        //[Description("ANES ISO ")] MDC_CONC_AWAY_ISOFL = 152040,
        //[Description("ANES N2O ")] MDC_CONC_AWAY_N2O = 152048,
        //[Description("ANES O2 ")] MDC_CONC_AWAY_O2 = 151908,
        //[Description("ANES SEV ")] MDC_CONC_AWAY_SEVOFL = 152036,
        //[Description("ANES SPO2 ")] MDC_PULS_OXIM_PLETH = 150452,
        //[Description("VENT CO2 ")] MDC_CONC_AWAY_CO2 = 151700,
        //[Description("VENT Flow ")] MDC_FLOW_AWAY = 151764,
        //[Description("VENT Paw ")] MDC_PRESS_AWAY = 151792,
        //[Description("VENT SPO2 ")] MDC_PULS_OXIM_PLETH = 150452,
        //[Description("VENT Volume ")] MDC_VOL_AWAY = 152708,
    }
}
